language: minimal
dist: xenial
services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/main/bin/travis-bootstrap | bash
  - cip before-install

install:
  - cip diag
  - cip install

script:
  - cip script

jobs:
  include:
    - env: CIP_TAG=static
    - env: CIP_TAG=5.33
    - env: CIP_TAG=5.32
    - env: CIP_TAG=5.30
    - env: CIP_TAG=5.28
    - env: CIP_TAG=5.26
    - env: CIP_TAG=5.24
    - env: CIP_TAG=5.22
    - env: CIP_TAG=5.20
    - env: CIP_TAG=5.18
    - env: CIP_TAG=5.16

branches:
  only:
    - master
    - main

cache:
  directories:
    - "$HOME/.cip"
